### ISSUE TITLE
Add customOperators example to storybook/sandbox examples

### ISSUE THREAD

**Issue by bmv437** [isobar-us/redux-form-gen#19]
### Tasks
* [ ] Add examples of using the new `customOperators` functionality that was added in #18 
	* [ ] to storybook (`/stories/index.js`)
	* [ ] to `examples/custom-operators`
